###############################################################
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "verifiable-credential-revocation-service.fullname" . }}
  labels:
    {{- include "verifiable-credential-revocation-service.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "verifiable-credential-revocation-service.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.vcrs.replicaCount }}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        {{- include "verifiable-credential-revocation-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "verifiable-credential-revocation-service.fullname" . }}
          image: {{ .Values.vcrs.image.repository }}:{{ default .Chart.AppVersion .Values.vcrs.image.tag }}
          imagePullPolicy: {{ .Values.vcrs.image.pullPolicy }}
          resources:
            {{- toYaml .Values.vcrs.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.vcrs.secretName }}
            - configMapRef:
                name: {{ .Values.vcrs.configName }}
          {{- with .Values.vcrs.livenessProbe }}
          {{- if .enabled }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- end }}
          {{- with .Values.vcrs.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            successThreshold: {{ .successThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- end }}