name: Snyk Scan
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main 
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_USERNAME: ${{ github.actor }}
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: snyk.sarif