name: Snyk Scan
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main 
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}